// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdkrxrdpvrrzkedqofeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpka3J4cmRwdnJyemtlZHFvZmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5Njc2NzgsImV4cCI6MjA2MTU0MzY3OH0.JXU6pvifIHem8-t4U1AuOfSUzUtUBq9_aJKJPlQOPBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);